<a href="https://colab.research.google.com/github/harshit01422-pixel/Python-Lab/blob/main/Preprocessing_on_Dataset_and_dealing_with_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Experiment 12
## To perform preprocessing on a dataset and dealing with missing values
### Name : Harshit
### PRN : 25070123053
### Batch : A-3

In [1]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'c1':[11,21, np.nan],'c2':[15, np.nan, np.nan],
                  'c3':[10,20,30]})
df1

     c1    c2  c3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [2]:
df1

     c1    c2  c3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [3]:
df1.isna() #Boolean Function

      c1     c2     c3
0  False  False  False
1  False   True  False
2   True   True  False

In [4]:
df1.notna()

      c1     c2    c3
0   True   True  True
1   True  False  True
2  False  False  True

In [5]:
df1.isna().sum() #columnwise na values

c1    1
c2    2
c3    0
dtype: int64

In [6]:
df1.dropna() #NaN rows are dropped

     c1    c2  c3
0  11.0  15.0  10

In [7]:
df1

     c1    c2  c3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [8]:
df1.fillna(value='DEFAULT')

        c1       c2  c3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [9]:
df1.fillna(df1.mean()) #Mean values of columns are calculated

     c1    c2  c3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [13]:
# Preprocessing on Dataset-1
import pandas as pd

data = {
    "Roll_No":[101,102,103,104],
    "Name":['Harshit',"Kshitij","Khush","Dahiwade"],
    "Age":[18,"-",21,"67"],
    "Marks":[85,90,"-",99],
    "Department":["CSE","IT","E&TC","cse"],
    "Admission_Date":["01-06-2023","03-06-2023","05-06-2023","07-06-2023"]
}
df = pd.DataFrame(data)
#Save as CSV
df.to_csv("student_data.csv",index=False)
df

   Roll_No      Name Age Marks Department Admission_Date
0      101   Harshit  18    85        CSE     01-06-2023
1      102   Kshitij   -    90         IT     03-06-2023
2      103     Khush  21     -       E&TC     05-06-2023
3      104  Dahiwade  67    99        cse     07-06-2023

In [16]:
import pandas as pd
import numpy as np
#Step 1
df = pd.read_csv("student_data.csv")
print("Original Data")
print(df)

Original Data
   Roll_No      Name Age Marks Department Admission_Date
0      101   Harshit  18    85        CSE     01-06-2023
1      102   Kshitij   -    90         IT     03-06-2023
2      103     Khush  21     -       E&TC     05-06-2023
3      104  Dahiwade  67    99        cse     07-06-2023

In [17]:
df.replace("-",np.nan, inplace=True)
df

   Roll_No      Name  Age Marks Department Admission_Date
0      101   Harshit   18    85        CSE     01-06-2023
1      102   Kshitij  NaN    90         IT     03-06-2023
2      103     Khush   21   NaN       E&TC     05-06-2023
3      104  Dahiwade   67    99        cse     07-06-2023

In [18]:
# Step 2 : Replace '-' with NaN to mark missing values
df.replace("-",np.nan,inplace=True)
#Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors='coerce')
df["Marks"] = pd.to_numeric(df["Marks"], errors='coerce')
'''When converting data (like strings → datetime),
if some values are invalid or cannot be converted,
instead of throwing an error, it will :
Replace those invalid values with NaT (not a time)'''
df

   Roll_No      Name   Age  Marks Department Admission_Date
0      101   Harshit  18.0   85.0        CSE     01-06-2023
1      102   Kshitij   NaN   90.0         IT     03-06-2023
2      103     Khush  21.0    NaN       E&TC     05-06-2023
3      104  Dahiwade  67.0   99.0        cse     07-06-2023

In [19]:
# Step 3 : Check missing values
print("\nMissing Values")
print(df.isnull().sum())

Missing Values
Roll_No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [20]:
# fill missing age with mean
df["Age"].fillna(df["Age"].mean(),inplace=True)

/tmp/ipykernel_383/139680913.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [21]:
# Fill missing marks with median
df["Marks"].fillna(df["Marks"].median(),inplace=True)

/tmp/ipykernel_383/654173197.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(),inplace=True)

In [22]:
df

   Roll_No      Name        Age  Marks Department Admission_Date
0      101   Harshit  18.000000   85.0        CSE     01-06-2023
1      102   Kshitij  35.333333   90.0         IT     03-06-2023
2      103     Khush  21.000000   90.0       E&TC     05-06-2023
3      104  Dahiwade  67.000000   99.0        cse     07-06-2023

In [23]:
print(df.isnull().sum())

Roll_No           0
Name              0
Age               0
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [24]:
# Step 5 : Fix inconsistent text formatting
df["Department"] = df["Department"].str.upper()

In [26]:
# Step 6 : Convert Admission_Date to standard datetime format
df["Admission_Date"]= pd.to_datetime(df["Admission_Date"], errors='coerce')

'''If a value cannot be converted to a valid date, pandas will replace it with NaT (Not a Time) instead of giving an error
Example : invalid dates like "abc", or "32-13-2024" become NaT'''

'If a value cannot be converted to a valid date, pandas will replace it with NaT (Not a Time) instead of giving an error\nExample : invalid dates like "abc", or "32-13-2024" become NaT'

In [27]:
#Step 7 : Show cleaned data
print("\nCleaned Data")
print(df)

Cleaned Data
   Roll_No      Name        Age  Marks Department Admission_Date
0      101   Harshit  18.000000   85.0        CSE     2023-01-06
1      102   Kshitij  35.333333   90.0         IT     2023-03-06
2      103     Khush  21.000000   90.0       E&TC     2023-05-06
3      104  Dahiwade  67.000000   99.0        CSE     2023-07-06

In [28]:
#Step 8 : Save cleaned dataset
df.to_csv("cleaned_student_data.csv",index=False)
print("\nCleaned CSV file saved as cleaned_student_data.csv")

Cleaned CSV file saved as cleaned_student_data.csv

In [29]:
# Working on missing values on Dataset-2
df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.isna().sum() #Attributes are displayed

In [36]:
#Imputing the missing value
#1. Luggage Room
df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())

/tmp/ipykernel_383/11879978.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Luggage.room']=df['Luggage.room'].fillna(df['Luggage.room'].mean())

In [35]:
#2. Rear.seat.room
df['Rear.seat.room']=df['Rear.seat.room'].fillna(df['Rear.seat.room'].mean())

/tmp/ipykernel_383/413999792.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Rear.seat.room']=df['Rear.seat.room'].fillna(df['Rear.seat.room'].mean())

In [33]:
#3.AirBags
df['AirBags']=df['AirBags'].fillna(df['AirBags'].mode().values[0])

In [34]:
#Save cleaned dataset
df.to_csv("cleaned_Cars93.csv",index=False)
print("\nCleaned CSV file saved as cleaned_Cars93.csv")

Cleaned CSV file saved as cleaned_Cars93.csv